### ISSUE TITLE
Unexpected behavior related to the connection settings dialog

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#366]
#### Software versions 
Briefcase v1.9.0

#### Problem description
Given that a user doesn't select the "remember passwords" setting, when opening the connection settings dialog, then the current password from the `ServerConnectionInfo` object that's saved in memory on each `PullTransferPanel` and `PushTransferPanel` is removed.

If the user just cancels the dialog after that, the next pull would fail (we have lost the password). To prevent this problem, in #365 we changed it so that **the forms table gets cleared, which is very confusing**.

#### Steps to reproduce the problem
- Ensure that "remember passwords" setting is not selected
- Pull some forms from an Aggregate server
- Open the connection dialog and click on cancel
- The forms table gets cleared

#### Proposed solution
The problem is twofold:
- The UI component for form source/target configuration is kind of confusing because it doesn't have a UX flow that clearly separates a "configured" state from a "not configured" state.
- The UI code and the business logic are quite coupled between them and other parts of Briefcase.

I think that solving just one thing is not going to cut it. That's why I'd like to propose to work on a new UI component that will replace current form source/target selection:
- It has to visually separate "configured" and "not configured" states
- The UI code has to be self-contained. It has to be easily reusable and testable in isolation.
- The relied upon business logic has to be side-effect free and has to make it easy to know the validness of a given form source/target configuration.

I propose to work on this without touching the existing code, to lower the risk of accidentally affecting other coupled parts of Briefcase. After completing this, we should remove any unused part of the "old" code.

After conversations with @yanokwa and @lognaturel, they also propose we get rid of the mounted SD card option. It's something that Briefcase doesn't really need, now that modern Android devices let you mount their filesystem locally. The custom directory option is enough for that.

The following UX flow represents these ideas (ignore any SD Card reference):
![briefcase_mockup_1](https://user-images.githubusercontent.com/205913/36172883-8c24dd10-1107-11e8-9c20-e752bf305a99.jpg)
![briefcase_mockup_2](https://user-images.githubusercontent.com/205913/36172885-8c51d3d8-1107-11e8-8d00-7f8cf918176f.jpg)
![briefcase_mockup_4](https://user-images.githubusercontent.com/205913/36172887-8c8ab536-1107-11e8-96eb-510028f5fdef.jpg)

### Task checklist

These are "broad stroke" tasks. It's more like an implementation script to try to follow an incremental approach to the solution. We build progressively from small to large.

- [ ] Create a UI form for the Aggregate server connection params dialog and a component that uses it as a view.
  - Credentials are optional
  - [ ] If the user clicks on the "OK" button, the connection params (url & credentials) have to be tested
    - [ ] If params are wrong, show error dialog and don't close the dialog
  - [ ] If the user clicks on the "Cancel" button, close the dialog
- [ ] Create a component that reacts to the user's interaction in the "source type selection" view
  - [ ] Create separate UI forms for "source type selection" view and "source type selected" views for Aggregate server and custom dir source types
  - [ ] If the user selects "Aggregate server", the connection params dialog is launched
    - [ ] If the user cancels, go back to "source type selection" view
    - [ ] If the user clicks "OK" (we assume the params are OK because the dialog verifies it), go to "source type selected" view for Aggregate server 
  - [ ] If the user selects "Custom dir", the `FileChooser` is launched
    - [ ] If the user cancels, go back to "source type selection" view
    - [ ] If the user clicks "OK" (we assume the params are OK because the dialog verifies it), go to 
  - [ ] The parent view (the pull/push tab) must be able to react to the users selection

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by ggalmazor** [comment]
@opendatakit-bot unlabel "contributor friendly"

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
@opendatakit-bot unlabel "needs discussion"

**Comment by mayank8318** [comment]
@opendatakit-bot claim

**Comment by mayank8318** [comment]
@ggalmazor What should be the task split up?

**Comment by ggalmazor** [comment]
> What should be the task split up?

I'll have it prepared in the next hours or so ;)

**Comment by mayank8318** [comment]
So I have to create first create two top fragments right?
One for when nothing is selected and one for when one of the sources is selected.

Firstly, I will make the Aggregate server config form and test it. Where should I put the UI component?

**Comment by ggalmazor** [comment]
> So I have to create first create two top fragments right?
> One for when nothing is selected and one for when one of the sources is selected.

Yep

> Firstly, I will make the Aggregate server config form and test it. Where should I put the UI component?

I'm thinking `org.opendatakit.briefcase.ui.reused`. Let's place it there and see how it feels :)

**Comment by mayank8318** [comment]
@ggalmazor I am not being able to resize the textfields, the jpanel is not expanding.
![screenshot from 2018-02-28 12-35-00](https://user-images.githubusercontent.com/22395998/36774437-13cc00d6-1c84-11e8-91a0-f2685945bf3b.png)

**Comment by ggalmazor** [comment]
Don't worry, @mayank8318, it's not so easy ;)

- Ensure all JPanels use `GridBagLayout` as Layout Manager
- Give the field a "Weight X" of `1.0`

With that, you'll be able to make those fields use all the horizontal space.

Take a look to `ConfigurationDialogForm.form` and mirror what we do there. Particularly:
- Spacers around the content
- Vertical spacer between content and the bottom actions panel
- Negative actions to the left (cancel button)
- Positive actions to the right (OK button)

**Comment by mayank8318** [comment]
Ok so it is similar to the weight param in a linearLayout in Android

**Comment by mayank8318** [comment]
@opendatakit-bot Working on it!

**Comment by mayank8318** [comment]
@opendatakit-bot claim

**Comment by mayank8318** [comment]
@opendatakit-bot Yep working on it

**Comment by ggalmazor** [comment]
Closing in favor of #366
